### PR TITLE
Fine Tuning permissions and descriptions.

### PR DESCRIPTION
**Pull request by TheMysticS**

### CODE REVIEW

**Comment by TheMysticS** [comment]
There were a couple of small errors (e.g. aren't should have been aren\'t) in Update APerm.kt (commit https://github.com/d4rken-org/permission-pilot/pull/132/commits/3fb4f2ec218d7d565266bba6f0ff1b2ebfea6c3f).  

I tried merging with my main branch and it completed successfully. But here it is showing the cross mark. Is it fine or do I close this PR and create a new one?

**Review by d4rken — APPROVED** [review]
lgtm :+1:

**Comment by TheMysticS** [comment]
> lgtm :+1: 

The changes that were showing errors (which were corrected in the new PR) are not reflecting in the app after the update. I'll include these again in the next PR.

**Comment by TheMysticS** [comment]
I updated my Fork with your main branch, and all changes done are showing in the APerm.kt and Strings.xml files. But why only some changes are showing in the app? I'm on the latest version (v0.7.1.1 RC).

**Pull request merged**
