### PR TITLE
Mystic branch

### PR DESCRIPTION
**Pull request by TheMysticS**
3 new permissions added.

### CODE REVIEW

**Comment by TheMysticS** [comment]
Please let me know why this is failing.

**Comment by dragonGod97677** [comment]
@TheMysticS 
Screenshot_2022-07-29-04-23-48-05

**Review by dragonGod97677 — COMMENTED** [review]
Rename the file, add .xml

**Comment by TheMysticS** [comment]
Thank you.

**Comment by TheMysticS** [comment]
Still failing.

**Review by dragonGod97677 — CHANGES_REQUESTED** [review]
The error log points this file and at line 139 but i don't see anything wrong on it.
Screenshot_2022-07-29-04-54-44-66



Line 137, try removing that space? 
[Screenshot_2022-07-29-04-52-14-10](https://user-images.githubusercontent.com/38875906/181635413-09c0803a-78e2-4128-8a91-dbe97faeee06.png)

**Comment by TheMysticS** [comment]
> The error log points this file (strings.xml) and at line 139 but i don't see anything wrong on it. Screenshot_2022-07-29-04-54-44-66
> 
> Line 137, try removing that space? [Screenshot_2022-07-29-04-52-14-10](https://user-images.githubusercontent.com/38875906/181635413-09c0803a-78e2-4128-8a91-dbe97faeee06.png)

Line 137 is not part of any changes being done. That one has already passed the test.

**Comment by dragonGod97677** [comment]
Sorry, i ran out of ideas on how it will not fail, the errors is all still the same. I've check the files you modified and nothing seems wrong on those files yet errors comes

**Comment by TheMysticS** [comment]
> Sorry, i ran out of ideas on how it will not fail, the errors is all still the same. I've check the files you modified and nothing seems wrong on those files yet errors comes

I'll try to see if I can pick something (basically trial & error :)). If not, we'll have to wait for @d4rken .

**Comment by TheMysticS** [comment]
Can I close this PR with 51 commits and create a new one with just 1 commit that contains all changes that have been done?

**Comment by TheMysticS** [comment]
And how can that be done?

**Pull request closed without merging**
