### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by gallegonovato**

### CODE REVIEW

**Comment by d4rken** [comment]
Thanks!

Are these the changes you mentioned in https://github.com/d4rken-org/permission-pilot/pull/180#pullrequestreview-1519105091
?

**Comment by gallegonovato** [comment]
Good afternoon:

Yes the changes are those.

Although I don't know if you made more changes to the initial strings.xml.

If not the only thing in case there are any changes that I did not see, upload everything again translated?

Best regards


________________________________
De: Matthias Urhahn ***@***.***>
Enviado: viernes, 7 de julio de 2023 19:06
Para: d4rken-org/permission-pilot ***@***.***>
Cc: gallegonovato ***@***.***>; Author ***@***.***>
Asunto: Re: [d4rken-org/permission-pilot] Update strings.xml (PR #189)


Thanks!

Are these the changes you mentioned in #180 (review)<https://github.com/d4rken-org/permission-pilot/pull/180#pullrequestreview-1519105091>
?

**Comment by d4rken** [comment]
Thanks. I think only those were changed. Google complained that some text was not according to policy :roll_eyes:.

**Comment by gallegonovato** [comment]
Good afternoon @d4rken


The blissful Google...... 

If only they would do things right instead of thumb their noses at honest developers.

I don't know if the other files need to change anything? Or in another of your applications?

I am here to help you :)

Best regards.

**Comment by d4rken** [comment]
> I don't know if the other files need to change anything? Or in another of your applications?

I hope not :sweat:. They don't need to make extra work for me.

> I am here to help you :)

Thank you :heart:

**Comment by gallegonovato** [comment]
Good afternoon:

As they say around here:  It just says I'll try to help as quickly as possible

A hug

**Pull request merged**
