### PR TITLE
Reworded permission restrictions statement.

### PR DESCRIPTION
**Pull request by TheMysticS**
Reworded the permission grant status statement for apps in other profiles.

### CODE REVIEW

**Comment by d4rken** [comment]
FYI: I can probably merge this with a squash, but before creating new PRs you should update your fork with the latest data.
Commonly, you create an extra branch with your changes, send a PR to merge that into the upstream repo (this). And after it's merged the extra branch is deleted, and you update the main branch with with the latest changes, from which you can then branch again to send  a new PR.

i.e. this PR contains all the commits again from yesterdays PR.

**Review by d4rken — APPROVED** [review]
Change looks good :+1:

**Comment by TheMysticS** [comment]
> FYI: I can probably merge this with a squash, but before creating new PRs you should update your fork with the latest data.
> Commonly, you create an extra branch with your changes, send a PR to merge that into the upstream repo (this). And after it's merged the extra branch is deleted, and you update the main branch with with the latest changes, from which you can then branch again to send  a new PR.
> 
> i.e. this PR contains all the commits again from yesterdays PR.

Okay. Will try this out from next time.

**Comment by TheMysticS** [comment]
I'm seeing 6 or more branches here:

https://github.com/TheMysticS/mystic-permissions/branches

Is it safe to delete them all and start a new branch?

**Pull request merged**
